spring:
  config:
    import: application-secret.properties
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DEV_DB_ENDPOINT}:5432/postgres?currentSchema=${DEV_DB_SCHEMA}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        auto_quote_keyword: true
        format_sql: true
        use_sql_comments: true
        highlight_sql: true

    hibernate:
      ddl-auto: update

logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE

aws-property:
  s3-bucket-name: ${S3_BUCKET_NAME}
  aws-region: ${S3_REGION}
  access-key: ${S3_ACCESS_KEY}
  secret-key: ${S3_SECRET_KEY}