spring:
  config:
    import: application-secret.properties
    activate:
      on-profile: dev
  datasource:
    driver-class-name:
    url:
    username:
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        auto_quote_keyword: true
        format_sql: true
        use_sql_comments: true
        highlight_sql: true

    hibernate:
      ddl-auto: update

logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE