spring:
  config:
    import: application-secret.properties
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        auto_quote_keyword: true
        format_sql: true
        use_sql_comments: true
        highlight_sql: true

    hibernate:
      ddl-auto: create

logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE

aws-property:
  s3-bucket-name: ${S3_BUCKET_NAME}
  s3-region: ${S3_REGION}
  s3-access-key: ${S3_ACCESS_KEY}
  s3-secret-key: ${S3_SECRET_KEY}