spring:
  config:
    import: application-secret.yml
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        auto_quote_keyword: true
        format_sql: true
        use_sql_comments: true
        highlight_sql: true

    hibernate:
      ddl-auto: create

logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE